### ISSUE TITLE
点模块关闭，首先不但清空了模块内部文案，还删除了其他无关模块，继续点击继续删除

### ISSUE THREAD

**Issue by lvxwww** [MasonEast/MasonEast.github.io#1]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/32978563/182753393-ab79708f-3fac-4a61-a8cf-222e3d3f9cae.png">

点击前端开发模块的关闭按钮，清除顺序如下
1.前端开发模块文字清除，个人作品模块2删除
2.从个人作品逐步向上删除模块

**Comment by MasonEast** [comment]
感谢，已优化第二版
